spring.application.name=DemoKafka

spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

logging.level.org.springframework.jdbc=DEBUG
logging.level.com.zaxxer.hikari=DEBUG


retryabletask:
    limit: 100
    timeoutInSeconds: 36000